### PR TITLE
Add functions

### PR DESCRIPTION
**Pull request by rozmar**
- made package pip installable
- added a generic python gitignore
- moved 2 of Mohit's scripts into functions
- moved jupyter notebooks in separate folder

### CODE REVIEW

**Comment by m2kulkarni** [comment]
Looks good to me! 

However we should be careful that no one touches each others jupyter notebooks since there is no way we can check the changes in github commits/PRs.

**Comment by rozmar** [comment]
That's a good point!
btw I don't like jupyter notebooks at all,  I think cells in spyder are much more useful for this purpose and more.
I've added more detailed explanation to the docstring you wrote.
This epoch stuff is not clear to me, why epoch keys are not consistent between sessions?

**Comment by m2kulkarni** [comment]
I dont know why the epoch keys are not consistent between sessions. Kayvon told me that it has something to do with how the data is collected. For eg, if the epoch values for day 1 is [1,1,3,3,3,3,3,3,4]  then 1 corresponds to preSpont, 3 is closed loop and 4 is postSpont. I think @kpdaie would be better able to say why this is so.

**Comment by m2kulkarni** [comment]
> I think cells in spyder are much more useful for this purpose and more.

I dont have any experience working with spyder but i agree with your thoughts on jupyter notebooks. However, what we can do is keep the notebooks as a way to validate all the functions. What i mean by this is, if someone adds a function, they should also add a block to the notebook explaining how it works and what it plots. This might however be redundant.

**Review by kpdaie — APPROVED** [review]
nice

**Pull request merged**
